# Live Trading Configuration

# Kalshi API Credentials
# Set these as Railway environment variables for security:
# KALSHI_EMAIL, KALSHI_PASSWORD, KALSHI_API_KEY, KALSHI_API_SECRET
api_credentials:
  email: ""  # Set via KALSHI_EMAIL environment variable
  password: ""  # Set via KALSHI_PASSWORD environment variable
  api_key: ""  # Set via KALSHI_API_KEY environment variable
  api_secret: ""  # Set via KALSHI_API_SECRET environment variable

# Trading Parameters
trading:
  # Starting bankroll (in dollars)
  bankroll: 500

  # Maximum exposure per game (50% = half your bankroll)
  max_exposure_pct: 0.20

  # Kelly fraction (0.15 = 1/4 Kelly, conservative)
  kelly_fraction: 0.15

  # Strategy parameters
  pregame_favorite_threshold: 0.60  # Only trade games with >60% pregame favorite
  trigger_threshold: 0.50  # Enter when price drops below 50%

  # Revert bands (exit targets)
  revert_bands: [0.55, 0.60, 0.65, 0.70]

  # Scaling levels (price in cents, Kelly multiplier)
  scaling_levels:
    - trigger: 49
      kelly_mult: 1.0
    - trigger: 45
      kelly_mult: 1.5
    - trigger: 41
      kelly_mult: 2.0
    - trigger: 37
      kelly_mult: 2.5
    - trigger: 33
      kelly_mult: 3.0

# Sports to trade
markets:
  nfl:
    enabled: true
    series_ticker: "KXNFLGAME"

  cfb:
    enabled: true  # Set to false if you only want NFL
    series_ticker: "KXNCAAFGAME"

# Risk Management
risk:
  # Maximum number of simultaneous games
  max_concurrent_games: 5

  # Maximum loss per game (in dollars)
  max_loss_per_game: 500

  # Stop trading if bankroll drops below this amount
  min_bankroll: 50

  # Enable dry run mode (paper trading, no real orders)
  dry_run: false  # Live trading enabled - set to true for paper trading

# Monitoring
monitoring:
  # How often to check prices (in seconds)
  poll_interval: 10

  # How far ahead to look for games (in hours)
  lookahead_hours: 6

  # Log file path
  log_file: "logs/live_trading.log"

  # Enable Telegram/Discord alerts (optional)
  telegram:
    enabled: false
    bot_token: ""
    chat_id: ""

# Safety Checks
safety:
  # Require manual confirmation before placing orders
  require_confirmation: true

  # Maximum order size (number of contracts)
  max_contracts_per_order: 100

  # Maximum total capital at risk across all games
  max_total_exposure: 500
